### ISSUE TITLE
Bug with alignment of other chrome tabs not displaying properly

### ISSUE THREAD

**Issue by kailash1998s** [shakthinandana/Write_Right#8]
Attached examples of the alignmenmet issue along with the error displayed.
![image](https://user-images.githubusercontent.com/33500369/135644530-ba284968-a114-4fdb-8feb-8a3c243e1ed7.png)
![image](https://user-images.githubusercontent.com/33500369/135644634-3c059d71-e0f5-42de-9855-0756610b8152.png)
![image](https://user-images.githubusercontent.com/33500369/135644666-bb2e1e21-2650-4d59-901f-e344a6f5569f.png)

**Comment by Ashwinshankar98** [comment]
Thanks for pointing it out 😅. I have made the necessary changes to the manifest.json and pushed it.
